import type { TaskGroup } from "./Task_Board";

export const initialTaskGroups = [
  {
    title: "To Be Assigned",
    dotClass: "dot-pending",
    badgeClass: "badge-pending",
    tasks: [
      {
        id: 1,
        task: "SCHEDULER SYSTEM FOR CYBENCE IT SOLUTIONS",
        creator: "Admin",
        assignedTo: "Perpaulo",
        createdOn: "2026-07-21",
        status: "Pending",
        dueDate: "2026-07-25",
        priority: "High",
      },
      {
        id: 2,
        task: "ALGORITHM OPTIMIZATION FOR ABCD COMPANY'S WEBSITE",
        creator: "Admin",
        assignedTo: "Sarah Chen",
        createdOn: "2026-07-18",
        status: "Pending",
        dueDate: "2026-07-25",
        priority: "Medium",
      },
    ],
  },
  {
    title: "To Do",
    dotClass: "dot-todo",
    badgeClass: "badge-todo",
    tasks: [
      {
        id: 3,
        task: "DESIGN AND IMPLEMENTATION OF A NEW USER INTERFACE FOR XYZ APPLICATION",
        creator: "Daniel",
        assignedTo: "Mae",
        createdOn: "2026-07-19",
        status: "To Do",
        dueDate: "2026-07-27",
        priority: "Low",
      },
      {
        id: 4,
        task: "DEVELOPMENT OF A MOBILE APPLICATION FOR E-COMMERCE PLATFORM",
        creator: "Mae",
        assignedTo: "Daniel",
        createdOn: "2026-07-17",
        status: "To Do",
        dueDate: "2026-07-27",
        priority: "Medium",
      },
    ],
  },
  {
    title: "Ongoing",
    dotClass: "dot-progress",
    badgeClass: "badge-progress",
    tasks: [
      {
        id: 5,
        task: "IMPLEMENTATION OF A NEW PAYMENT GATEWAY FOR ABCD COMPANY",
        creator: "Janina",
        assignedTo: "Perpaulo",
        createdOn: "2026-07-16",
        status: "Ongoing",
        dueDate: "2026-07-30",
        priority: "Critical",
      },
      {
        id: 6,
        task: "ALGORITHM OPTIMIZATION FOR BYD COMPANY'S WEBSITE",
        creator: "Daniel",
        assignedTo: "Janina",
        createdOn: "2026-07-15",
        status: "Ongoing",
        dueDate: "2026-07-30",
        priority: "High",
      },
    ],
  },
  {
    title: "Completed",
    dotClass: "dot-completed",
    badgeClass: "badge-done",
    tasks: [
      {
        id: 7,
        task: "SCHEDULER SYSTEM FOR WWW SOLUTIONS",
        creator: "Admin",
        assignedTo: "Sarah Chen",
        createdOn: "2026-07-14",
        status: "Completed",
        dueDate: "2026-07-31",
        priority: "Low",
      },
      {
        id: 8,
        task: "WEB DEVELOPMENT FOR ABCD COMPANY",
        creator: "Admin",
        assignedTo: "Mae",
        createdOn: "2026-07-13",
        status: "Completed",
        dueDate: "2026-07-21",
        priority: "Medium",
      },
    ],
  },
  {
    title: "Unfinished",
    dotClass: "dot-unfinished",
    badgeClass: "badge-unfinished",
    tasks: [
      {
        id: 9,
        task: "SOFTWARE TESTING FOR XYZ APPLICATION",
        creator: "Admin",
        assignedTo: "Daniel",
        createdOn: "2026-07-12",
        status: "Unfinished",
        dueDate: "2026-07-21",
        priority: "High",
      },
      {
        id: 10,
        task: "HARDWARE INTEGRATION FOR ABCD COMPANY'S SYSTEM",
        creator: "Admin",
        assignedTo: "Perpaulo",
        createdOn: "2026-07-11",
        status: "Unfinished",
        dueDate: "2026-07-21",
        priority: "Low",
      },
    ],
  },
] as unknown as TaskGroup[];
